name: Go

on:
  push:
    branches: [ master ]
    tags: ['*']
  pull_request:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:

    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23.2

    - name: Run linter
      run: go install github.com/mgechev/revive@latest && revive -formatter friendly ./...

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test --cover -v ./... 

    - name: build
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        mkdir -p build
        GOOS=linux GOARCH=amd64 go build -o build/orchestrator-linux-amd64 cmd/orchestrator/orchestrator.go
        GOOS=linux GOARCH=arm64 go build -o build/orchestrator-linux-arm64 cmd/orchestrator/orchestrator.go
        GOOS=linux GOARCH=386 go build -o build/orchestrator-linux-386 cmd/orchestrator/orchestrator.go
        GOOS=windows GOARCH=amd64 go build -o build/orchestrator-windows-amd64.exe cmd/orchestrator/orchestrator.go
        GOOS=windows GOARCH=arm64 go build -o build/orchestrator-windows-arm64.exe cmd/orchestrator/orchestrator.go
        GOOS=windows GOARCH=386 go build -o build/orchestrator-windows-386.exe cmd/orchestrator/orchestrator.go
        GOOS=darwin GOARCH=amd64 go build -o build/orchestrator-darwin-amd64 cmd/orchestrator/orchestrator.go
        GOOS=darwin GOARCH=arm64 go build -o build/orchestrator-darwin-arm64 cmd/orchestrator/orchestrator.go
        GOOS=linux GOARCH=amd64 go build -o build/agent-linux-amd64 cmd/agent/agent.go
        GOOS=linux GOARCH=arm64 go build -o build/agent-linux-arm64 cmd/agent/agent.go
        GOOS=linux GOARCH=386 go build -o build/agent-linux-386 cmd/agent/agent.go
        GOOS=windows GOARCH=amd64 go build -o build/agent-windows-amd64.exe cmd/agent/agent.go
        GOOS=windows GOARCH=arm64 go build -o build/agent-windows-arm64.exe cmd/agent/agent.go
        GOOS=windows GOARCH=386 go build -o build/agent-windows-386.exe cmd/agent/agent.go
        GOOS=darwin GOARCH=amd64 go build -o build/agent-darwin-amd64 cmd/agent/agent.go
        GOOS=darwin GOARCH=arm64 go build -o build/agent-darwin-arm64 cmd/agent/agent.go

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/orchestrator-linux-amd64
          build/orchestrator-linux-arm64
          build/orchestrator-linux-386
          build/orchestrator-windows-amd64.exe
          build/orchestrator-windows-arm64.exe
          build/orchestrator-windows-386.exe
          build/orchestrator-darwin-amd64
          build/orchestrator-darwin-arm64
          build/agent-linux-amd64
          build/agent-linux-arm64
          build/agent-linux-386
          build/agent-windows-amd64.exe
          build/agent-windows-arm64.exe
          build/agent-windows-386.exe
          build/agent-darwin-amd64
          build/agent-darwin-arm64
          README.md